### Localhost testing
GET http://localhost:3000/items

### Localhost testing
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Testing 2"
}

### Localhost testing
GET http://52.73.34.215:8080/items